config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from catalog.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path
from .views import create_order


app_name = 'orders'

urlpatterns = [
    path("create_order/<slug:tour_slug>", create_order, name="create_order")
]

orders/models.py
from django.db import models

from catalog.models import Tour

ORDER_STATUS_CHOICES = (
    ('pending', 'pending'),
    ('approved', 'approved'),
    ('rejected', 'rejected'),
)


class Order(models.Model):
    status = models.CharField(
        verbose_name='Status',
        max_length=20,
        choices=ORDER_STATUS_CHOICES,
        default='pending'
    )
    tour = models.ManyToManyField(Tour, related_name='tour_orders', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Order - {self.pk}"


    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Order"
        verbose_name_plural = "Orders"
        indexes = [
            models.Index(fields=["-created_at"])
        ]

class OrderInfo(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE, related_name='info')
    first_name = models.CharField(verbose_name='First Name', max_length=50)
    last_name = models.CharField(verbose_name='Last Name', max_length=100)
    email = models.EmailField(verbose_name='Email', max_length=100)
    phone = models.CharField(verbose_name='Phone', max_length=200, blank=True)
    city = models.CharField(verbose_name='City', max_length=50, blank=True)
    members = models.PositiveIntegerField(verbose_name='Members', default=1)

    date_from = models.DateField(verbose_name='Start date', blank=True, null=True)
    date_to = models.DateField(verbose_name='End date', blank=True, null=True)

    def __str__(self):
        return f"Order info - {self.order.pk}: {self.first_name} {self.last_name}"


    class Meta:
        verbose_name = "Order information"

orders/forms.py
from django import forms
from orders.models import OrderInfo


MEMBERS_NUMBER_CHOICES = [(i, str(i)) for i in range(1, 8)]


class OrderInfoEditForm(forms.ModelForm):
    members = forms.TypedChoiceField(
            choices=MEMBERS_NUMBER_CHOICES,
            coerce=int,
            label="Количество человек",
            widget=forms.Select(attrs={"class": "form-select rounded-4", "style": "max-width: 300px;"})
        )
    class Meta:
        model = OrderInfo
        fields = '__all__'
        exclude = ['order','date_from', 'date_to']
        labels = {
            'first_name': '',
            'last_name': '',
            'email': '',
            'phone': '',
            'city': ''
        }
        widgets = {
            "first_name": forms.TextInput(attrs={
                "placeholder": "Имя",
                "class": "form-control rounded-4",
                "style": "max-width: 300px;"
            }),
            "last_name": forms.TextInput(attrs={
                "placeholder": "Фамилия",
                "class": "form-control rounded-4",
                "style": "max-width: 300px;"
            }),
            "email": forms.EmailInput(attrs={
                "placeholder": "Email",
                "class": "form-control rounded-4",
                "style": "max-width: 300px;"
            }),
            "phone": forms.TextInput(attrs={
                "placeholder": "Телефон",
                "class": "form-control rounded-4",
                "style": "max-width: 300px;"
            }),
            "city": forms.TextInput(attrs={
                "placeholder": "Город",
                "class": "form-control rounded-4",
                "style": "max-width: 300px;"
            })
        }

class DatePickerInput(forms.DateInput):
    input_type = 'date'


class DateEditForm(forms.Form):
    date_from = forms.DateField(
        label="Начало",
        widget=DatePickerInput(attrs={"class": "form-control rounded-4", "style": "max-width: 300px;"})
    )
    date_to = forms.DateField(
        label="Конец",
        widget=DatePickerInput(attrs={"class": "form-control rounded-4", "style": "max-width: 300px;"})
    )

orders/views.py
from django.shortcuts import render

from catalog.models import Tour
from orders.models import Order, OrderInfo
from .forms import OrderInfoEditForm, DateEditForm


def create_order(request, tour_slug):
    tour = Tour.objects.get(slug=tour_slug)
    if request.method == 'POST':
        form = OrderInfoEditForm(request.POST)
        date_form = DateEditForm(request.POST)
        if form.is_valid() and date_form.is_valid():
            order = Order.objects.create()
            order.tour.add(tour)
            OrderInfo.objects.create(
                order=order,
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                email=form.cleaned_data['email'],
                phone=form.cleaned_data['phone'],
                city=form.cleaned_data['city'],
                members=form.cleaned_data['members'],
                date_from=date_form.cleaned_data['date_from'],
                date_to=date_form.cleaned_data['date_to']
            )
            return render(request, "created.html", {"order": order})
    else:
        form = OrderInfoEditForm()
        date_form = DateEditForm()
    return render(request, "create.html",
    context={
        "form": form,
        "date_form": date_form,
        "tour": tour
    })

orders/templates/create.html
{% extends 'base.html' %}


{% block content %}
    <section class="w-50 mb-4 ms-auto me-auto mt-4">
        <div class="border rounded-3">
            <section class="px-3 py-5" style="background-color: white">
                <div class="mt-2">
                    <h3 class="mb-2 mt-2" style="text-align: center;">Информация о поездке</h3>
                    <p class="mb-4" style="text-align: center;">Оплата вноситься после согласования с нашим
                        менеджером</p>
                    <div class="row ms-2 me-2">
                        <div class="col p-2">
                            <form action="{% url 'orders:create_order' tour.slug %}" method="post">
                                <div class="col-md-12">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                </div>
                                <div class="col-md-12">
                                    {{ date_form.as_p }}
                                </div>
                                <button class="btn btn-outline-dark" type="submit" style="width: 300px;">Подтвердить
                                </button>
                            </form>
                        </div>
                        <div class="col p-2">
                            <div class="border border-dark rounded-3 me-4">
                                <div class="p-3">
                                    <h3>{{ tour.name }}</h3>
                                    <p>{{ tour.category.name }}</p>
                                    <p>{{ tour.destination.name }} ({{ tour.city }})</p>
                                    <h4>BYN {{ tour.price }}</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </section>
{% endblock %}

orders/templates/created.html
{% extends 'base.html' %}

{% block content %}
    <section class="w-75 mb-4 ms-auto me-auto mt-4">
        <div class="border rounded-3">
            <section class="px-3 py-5" style="background-color: white">
                <div class="row d-flex justify-content-center">
                    <div class="col-xl-11" style="text-align: center">
                        <h3>Спасибо за ваш заказ!</h3>
                        <p>Ваш номер {{ order.pk }}</p>
                        <p>Скоро наш менеджер перезвонит вам по указанному в закзазе номеру</p>
                    </div>
                </div>
            </section>
        </div>
    </section>


{% endblock %}